name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Pour une analyse complète
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.5.4"
      # Installer Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.3" # Remplace par la version de Flutter que tu utilises

      # Installer les dépendances Flutter
      - name: Install dependencies
        run: flutter pub get

      # Construire l'application Flutter pour Android
      - name: Build APK
        run: flutter build apk --release # Pour Android

      # Exécuter l'analyse SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
